on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - master
      - release
    tags:
      - v**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build
        run: ./bin/build.sh

      - name: Deploy
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: npx --package netlify-cli netlify deploy --dir=public --message="automatic deploy ${{ github.sha }}"
